more configurable chroot, dotfile updates

diff --git a/dotfiles/bash_aliases b/dotfiles/bash_aliases
--- a/dotfiles/bash_aliases
+++ b/dotfiles/bash_aliases
@@ -14,12 +14,36 @@ export PATH=$HOME/Code/Sysmods/scripts:$PATH
 export PATH=$HOME/Code/Sysmods/chroot:$PATH
 export PATH=$HOME/Scripts:$PATH
 
-source $HOME/Code/Sysmods/git-completion.bash
+function apath_adt()
+{
+    export PATH=$HOME/Android/adt-bundle-linux-x86_64-20130219/sdk/platform-tools/:$PATH
+    export PATH=$HOME/Android/adt-bundle-linux-x86_64-20130219/sdk/tools/:$PATH
+}
 
-export PS1="\[\033[31;38m\]\w\[\033[1;31m\]\$(__git_ps1)\[\033[00m\] "
-export GIT_PS1_SHOWDIRTYSTATE=1
+function apath_ndk()
+{
+    export PATH=$HOME/Android/android-ndk-r8e:$PATH
+}
 
 alias dirs='dirs -v'
+
+export COLOR_NC='\e[0m' # No Color
+export COLOR_WHITE='\e[1;37m'
+export COLOR_BLACK='\e[0;30m'
+export COLOR_BLUE='\e[0;34m'
+export COLOR_LIGHT_BLUE='\e[1;34m'
+export COLOR_GREEN='\e[0;32m'
+export COLOR_LIGHT_GREEN='\e[1;32m'
+export COLOR_CYAN='\e[0;36m'
+export COLOR_LIGHT_CYAN='\e[1;36m'
+export COLOR_RED='\e[0;31m'
+export COLOR_LIGHT_RED='\e[1;31m'
+export COLOR_PURPLE='\e[0;35m'
+export COLOR_LIGHT_PURPLE='\e[1;35m'
+export COLOR_BROWN='\e[0;33m'
+export COLOR_YELLOW='\e[1;33m'
+export COLOR_GRAY='\e[0;30m'
+export COLOR_LIGHT_GRAY='\e[0;37m'
 
 cd() {
    MAX=10
@@ -46,3 +70,64 @@ cd() {
       popd -n -0 > /dev/null
    fi
 }
+
+j_history_update() {
+    history -a
+    history -n
+}
+
+vboxdate () {
+   # Adjust VM BIOS time to a given date
+   secs=$(date --date="$2" +%s)    # convert supplied date to secs, since 1970-01-01
+   let secs-=$(date +%s)           # subtract the date NOW
+   msecs=$(( $secs * 1000 ))       # convert to millis
+   echo Adjusting time ${msecs}ms
+   echo VBoxManage modifyvm $1 --biossystemtimeoffset ${msecs};
+}
+
+export PATH="$HOME/.rbenv/bin:$PATH"
+
+if [ -n "`which rbenv`" ]; then
+    eval "$(rbenv init -)"
+fi
+
+if [ -n "$SCHROOT_CHROOT_NAME" ]; then
+
+    echo -n "`echo -e $COLOR_LIGHT_GREEN`>>>`echo -e $COLOR_NC` "
+    echo -n "Inside chroot named: $SCHROOT_CHROOT_NAME "
+    echo    "`echo -e $COLOR_LIGHT_GREEN`<<<`echo -e $COLOR_NC`"
+    echo
+
+    export PS1="$COLOR_LIGHT_RED{$SCHROOT_CHROOT_NAME}$COLOR_NC $PS1"
+    export DISPLAY=:0.0
+
+    xhost + &> /dev/null || (echo "Failed to setup X host access")
+fi
+
+#export UNDER_SCRIPT=1
+
+if [ -z "$UNDER_SCRIPT" ]; then
+
+    logdir=$HOME/Logs
+    logname=$(date +%F_%T).$$.script
+
+    logfile=$logdir/.$logname
+    final_logfile=$logdir/$logname
+
+    trap '( mv $logfile $final_logfile )' EXIT
+
+    if [ ! -d $logdir ]; then
+        mkdir $logdir
+    fi
+
+    gzip -q $logdir/*.script &>/dev/null
+
+    export UNDER_SCRIPT=$logfile
+
+    script -e -f -q $logfile
+    exit $?
+fi
+
+if [ -z "$SCHROOT_CHROOT_NAME" ]; then
+    shopt -s direxpand &> /dev/null || (echo "Failed to set direxpand option")
+fi
